# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170812_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.Wallet'),
        ),
    ]
